apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-api-rewriter-kubeconfig
  namespace: gpu-control-plane-local
data:
  kubeconfig: |
    # copy the contents of local/kube-api-rewriter.kubeconfig here
