{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
{{- $moduleValues := .Values.gpuControlPlane | default dict }}
{{- $internal := $moduleValues.internal | default dict }}
{{- $controller := $internal.controller | default dict }}
{{- $config := $controller.config | default dict }}
{{- if $config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpuControlPlane.controllerConfigName" . }}
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .))) | nindent 2 }}
data:
  config.yaml: |
{{ toYaml $config | indent 4 }}
{{- end }}
{{- end }}
