{{/* Copyright 2025 Flant JSC */}}
{{- $moduleValues := .Values.gpuControlPlane | default dict }}
{{- $monitoringValues := $moduleValues.monitoring | default dict }}
{{- $globalValues := .Values.global | default dict }}
{{- $enabledModules := $globalValues.enabledModules | default (list) }}
{{- $clusterDomain := $globalValues.discovery.clusterDomain }}
{{- $metricsServiceHost := printf "%s-metrics.%s.svc" (include "gpuControlPlane.controllerName" .) (include "gpuControlPlane.namespace" .) }}
{{- $metricsServiceFQDN := printf "%s.%s" $metricsServiceHost $clusterDomain }}
{{- if and (eq (include "gpuControlPlane.isEnabled" .) "true") (default false $monitoringValues.serviceMonitor) ($enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ include "gpuControlPlane.controllerName" . }}
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .) "prometheus" "main")) | nindent 2 }}
spec:
  honorLabels: true
  authorization:
    credentials:
      name: prometheus-token
      key: token
  scheme: HTTPS
  tlsConfig:
    serverName: {{ $metricsServiceFQDN }}
    ca:
      secret:
        name: {{ include "gpuControlPlane.monitoringCASecretName" . }}
        key: ca.crt
  metricsPath: /metrics
  staticConfigs:
    - targets:
        - '{{ $metricsServiceHost }}.{{ $clusterDomain }}.:8080'
{{- end }}
