{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpuControlPlane.gpuControllerName" . }}
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.gpuControllerName" .) "component" "controller")) | nindent 2 }}
spec:
  ports:
    - name: pprof
      port: 8081
      protocol: TCP
      targetPort: pprof
  selector:
    app: {{ include "gpuControlPlane.gpuControllerName" . }}
{{- end }}
