# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch: {}

env:
  GO_VERSION: "1.24.6"
  WERF_VERSION: "1.2.457"
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}
  MODULES_REGISTRY: ghcr.io
  MODULES_REGISTRY_LOGIN: ${{ github.actor }}
  MODULES_REGISTRY_PASSWORD: ${{ secrets.MODULES_REGISTRY_PASSWORD || secrets.TOKEN || secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: write

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/lint@v2
        with:
          dmt_version: 0.1.55
        env:
          DMT_METRICS_URL: ${{ secrets.DMT_METRICS_URL }}
          DMT_METRICS_TOKEN: ${{ secrets.DMT_METRICS_TOKEN }}

  tests:
    runs-on: ubuntu-latest
    name: Verify
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache-dependency-path: |
            src/controller/go.sum
            hooks/go.sum
      - name: Install werf
        env:
          WERF_VERSION: ${{ env.WERF_VERSION }}
        run: |
          curl -sSL https://werf.io/install.sh | sudo bash -s -- --version "${WERF_VERSION}"
      - name: Ensure tools
        run: make ensure-tools
      - name: Run lints and tests
        run: make verify
      - name: Controller coverage
        run: |
          cd src/controller
          go test ./... -coverprofile=controller.cover
          go tool cover -func=controller.cover
      - name: Hooks coverage
        run: |
          cd images/hooks
          go test ./... -coverprofile=hooks.cover
          go tool cover -func=hooks.cover
      - name: Kube API rewriter coverage
        run: |
          cd images/kube-api-rewriter
          go test ./... -coverprofile=rewriter.cover
          go tool cover -func=rewriter.cover
  build:
    needs:
      - lint
      - tests
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Build and push images
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ env.MODULES_REGISTRY }}
          registry_login: ${{ env.MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ env.MODULES_REGISTRY_PASSWORD }}
      - name: Get repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> "$GITHUB_OUTPUT"
      - uses: deckhouse/modules-actions/build@v4
        with:
          module_source: ghcr.io/${{ github.repository_owner }}/modules
          module_name: ${{ steps.repo_name.outputs.REPO_NAME }}
          module_tag: ${{ github.ref_name }}
